### ISSUE TITLE
Info panel is not responsive

### ISSUE THREAD

**Issue by C-Pro** [C-Pro/site-devfest-2019#5]
Info panel blows out on mobile devices.

![image](https://user-images.githubusercontent.com/1990084/60234557-0da0fe00-98e8-11e9-84d2-fdd2ad1a33ee.png)

I think corresponding styles are in https://github.com/C-Pro/devfest-theme-hugo/blob/master/src/style/pages/_home.scss

**Comment by Grawl** [comment]
resolved, not deployed, built assets not commited, theme submodule not updated: waiting for CI update* or CI update rejection

_CI update — I mean build CSS & JS on CI, not on developer machine, not commit built assets_
